// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SensorApp.Infrastructure;

#nullable disable

namespace SensorApp.Infrastructure.Migrations
{
    [DbContext(typeof(SensorAppDbContext))]
    [Migration("20230213154937_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SensorApp.Core.Entities.Sensor", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("RangeEnd")
                        .HasColumnType("int");

                    b.Property<int>("RangeStart")
                        .HasColumnType("int");

                    b.Property<string>("SensorType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Value")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("Sensors");

                    b.HasData(
                        new
                        {
                            Id = 7676L,
                            RangeEnd = 1000000,
                            RangeStart = 0,
                            SensorType = "Light",
                            Value = 603670f
                        },
                        new
                        {
                            Id = 4693L,
                            RangeEnd = 1000000,
                            RangeStart = 0,
                            SensorType = "Light",
                            Value = 166084f
                        },
                        new
                        {
                            Id = 6829L,
                            RangeEnd = 650,
                            RangeStart = -240,
                            SensorType = "Temperature",
                            Value = 182f
                        },
                        new
                        {
                            Id = 5855L,
                            RangeEnd = 650,
                            RangeStart = -240,
                            SensorType = "Temperature",
                            Value = 593f
                        },
                        new
                        {
                            Id = 9810L,
                            RangeEnd = 100,
                            RangeStart = 0,
                            SensorType = "Humidity",
                            Value = 90f
                        },
                        new
                        {
                            Id = 7472L,
                            RangeEnd = 1000000,
                            RangeStart = 0,
                            SensorType = "Light",
                            Value = 26370f
                        },
                        new
                        {
                            Id = 7275L,
                            RangeEnd = 1000000,
                            RangeStart = 0,
                            SensorType = "Light",
                            Value = 313963f
                        },
                        new
                        {
                            Id = 2068L,
                            RangeEnd = 650,
                            RangeStart = -240,
                            SensorType = "Temperature",
                            Value = 108f
                        },
                        new
                        {
                            Id = 2287L,
                            RangeEnd = 100,
                            RangeStart = 0,
                            SensorType = "Humidity",
                            Value = 60f
                        },
                        new
                        {
                            Id = 8837L,
                            RangeEnd = 650,
                            RangeStart = -240,
                            SensorType = "Temperature",
                            Value = 87f
                        },
                        new
                        {
                            Id = 5002L,
                            RangeEnd = 100,
                            RangeStart = 0,
                            SensorType = "Humidity",
                            Value = 54f
                        },
                        new
                        {
                            Id = 8099L,
                            RangeEnd = 1000000,
                            RangeStart = 0,
                            SensorType = "Light",
                            Value = 533453f
                        },
                        new
                        {
                            Id = 3191L,
                            RangeEnd = 1000000,
                            RangeStart = 0,
                            SensorType = "Light",
                            Value = 648391f
                        },
                        new
                        {
                            Id = 2581L,
                            RangeEnd = 650,
                            RangeStart = -240,
                            SensorType = "Temperature",
                            Value = 186f
                        },
                        new
                        {
                            Id = 8060L,
                            RangeEnd = 100,
                            RangeStart = 0,
                            SensorType = "Humidity",
                            Value = 97f
                        },
                        new
                        {
                            Id = 3021L,
                            RangeEnd = 100,
                            RangeStart = 0,
                            SensorType = "Humidity",
                            Value = 72f
                        },
                        new
                        {
                            Id = 5916L,
                            RangeEnd = 100,
                            RangeStart = 0,
                            SensorType = "Humidity",
                            Value = 53f
                        },
                        new
                        {
                            Id = 7701L,
                            RangeEnd = 100,
                            RangeStart = 0,
                            SensorType = "Humidity",
                            Value = 58f
                        },
                        new
                        {
                            Id = 7050L,
                            RangeEnd = 100,
                            RangeStart = 0,
                            SensorType = "Humidity",
                            Value = 44f
                        },
                        new
                        {
                            Id = 9918L,
                            RangeEnd = 650,
                            RangeStart = -240,
                            SensorType = "Temperature",
                            Value = -225f
                        },
                        new
                        {
                            Id = 9750L,
                            RangeEnd = 650,
                            RangeStart = -240,
                            SensorType = "Temperature",
                            Value = 464f
                        },
                        new
                        {
                            Id = 2859L,
                            RangeEnd = 650,
                            RangeStart = -240,
                            SensorType = "Temperature",
                            Value = 395f
                        },
                        new
                        {
                            Id = 3900L,
                            RangeEnd = 100,
                            RangeStart = 0,
                            SensorType = "Humidity",
                            Value = 48f
                        },
                        new
                        {
                            Id = 1315L,
                            RangeEnd = 650,
                            RangeStart = -240,
                            SensorType = "Temperature",
                            Value = 390f
                        },
                        new
                        {
                            Id = 6863L,
                            RangeEnd = 1000000,
                            RangeStart = 0,
                            SensorType = "Light",
                            Value = 300262f
                        },
                        new
                        {
                            Id = 8179L,
                            RangeEnd = 1000000,
                            RangeStart = 0,
                            SensorType = "Light",
                            Value = 4464f
                        },
                        new
                        {
                            Id = 9559L,
                            RangeEnd = 650,
                            RangeStart = -240,
                            SensorType = "Temperature",
                            Value = 170f
                        },
                        new
                        {
                            Id = 9694L,
                            RangeEnd = 100,
                            RangeStart = 0,
                            SensorType = "Humidity",
                            Value = 32f
                        },
                        new
                        {
                            Id = 5049L,
                            RangeEnd = 100,
                            RangeStart = 0,
                            SensorType = "Humidity",
                            Value = 65f
                        },
                        new
                        {
                            Id = 8688L,
                            RangeEnd = 1000000,
                            RangeStart = 0,
                            SensorType = "Light",
                            Value = 193326f
                        },
                        new
                        {
                            Id = 5773L,
                            RangeEnd = 1000000,
                            RangeStart = 0,
                            SensorType = "Light",
                            Value = 458732f
                        },
                        new
                        {
                            Id = 9129L,
                            RangeEnd = 1000000,
                            RangeStart = 0,
                            SensorType = "Light",
                            Value = 664018f
                        },
                        new
                        {
                            Id = 1755L,
                            RangeEnd = 100,
                            RangeStart = 0,
                            SensorType = "Humidity",
                            Value = 48f
                        },
                        new
                        {
                            Id = 6218L,
                            RangeEnd = 1000000,
                            RangeStart = 0,
                            SensorType = "Light",
                            Value = 817381f
                        },
                        new
                        {
                            Id = 4503L,
                            RangeEnd = 650,
                            RangeStart = -240,
                            SensorType = "Temperature",
                            Value = -91f
                        },
                        new
                        {
                            Id = 2830L,
                            RangeEnd = 650,
                            RangeStart = -240,
                            SensorType = "Temperature",
                            Value = 516f
                        },
                        new
                        {
                            Id = 5655L,
                            RangeEnd = 650,
                            RangeStart = -240,
                            SensorType = "Temperature",
                            Value = 44f
                        },
                        new
                        {
                            Id = 1623L,
                            RangeEnd = 100,
                            RangeStart = 0,
                            SensorType = "Humidity",
                            Value = 45f
                        },
                        new
                        {
                            Id = 7415L,
                            RangeEnd = 1000000,
                            RangeStart = 0,
                            SensorType = "Light",
                            Value = 898567f
                        },
                        new
                        {
                            Id = 7976L,
                            RangeEnd = 100,
                            RangeStart = 0,
                            SensorType = "Humidity",
                            Value = 10f
                        },
                        new
                        {
                            Id = 6199L,
                            RangeEnd = 1000000,
                            RangeStart = 0,
                            SensorType = "Light",
                            Value = 123642f
                        },
                        new
                        {
                            Id = 9450L,
                            RangeEnd = 1000000,
                            RangeStart = 0,
                            SensorType = "Light",
                            Value = 807216f
                        },
                        new
                        {
                            Id = 9136L,
                            RangeEnd = 650,
                            RangeStart = -240,
                            SensorType = "Temperature",
                            Value = 7f
                        },
                        new
                        {
                            Id = 8352L,
                            RangeEnd = 1000000,
                            RangeStart = 0,
                            SensorType = "Light",
                            Value = 919611f
                        },
                        new
                        {
                            Id = 1736L,
                            RangeEnd = 650,
                            RangeStart = -240,
                            SensorType = "Temperature",
                            Value = 200f
                        },
                        new
                        {
                            Id = 1645L,
                            RangeEnd = 650,
                            RangeStart = -240,
                            SensorType = "Temperature",
                            Value = 404f
                        },
                        new
                        {
                            Id = 8947L,
                            RangeEnd = 650,
                            RangeStart = -240,
                            SensorType = "Temperature",
                            Value = -56f
                        },
                        new
                        {
                            Id = 8248L,
                            RangeEnd = 650,
                            RangeStart = -240,
                            SensorType = "Temperature",
                            Value = 633f
                        },
                        new
                        {
                            Id = 5155L,
                            RangeEnd = 650,
                            RangeStart = -240,
                            SensorType = "Temperature",
                            Value = 385f
                        },
                        new
                        {
                            Id = 7177L,
                            RangeEnd = 100,
                            RangeStart = 0,
                            SensorType = "Humidity",
                            Value = 15f
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
